---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keel
  namespace: ${argo_cd_namespace}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
          - key: 'gperreymond/argocd-deployer-all'
            operator: In
            values:
              - 'true'
        values:
          targetRevision: '${keel.targetRevision}'
  template:
    metadata:
      name: '{{ .name }}-keel'
      namespace: ${argo_cd_namespace}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: shared
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
      sources:
        - repoURL: https://charts.keel.sh
          chart: keel
          targetRevision: '{{ .values.targetRevision }}'
          helm:
            releaseName: keel
            valueFiles:
              - $values/charts/remote-values/keel/global.yaml
        - repoURL: 'https://github.com/gperreymond/k8s-workflows.git'
          targetRevision: main
          ref: values
      destination:
        server: '{{ .server }}'
        namespace: ${kube_system_namespace}