---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-resources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-resources-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["watch", "list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch", "list", "get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-resources-role-binding
roleRef:
  kind: ClusterRole
  name: argo-resources-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: argo-resources
    namespace: argo-system