---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-workflows
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - 'websecure'
  routes:
    - kind: Rule
      match: 'Host(`argo-workflows.docker.localhost`)'
      services: 
        - kind: Service
          name: argo-workflows-server
          namespace: argo-system
          passHostHeader: true
          scheme: http
          port: 2746
